##spring.datasource.url=jdbc:postgresql://192.168.10.152:5432/authmanage
##spring.datasource.username=ecluser
##spring.datasource.password=skeletonecl
#
# Database Configuration
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://ep-floral-snow-aosnbcaa-pooler.c-2.ap-southeast-1.aws.neon.tech/browns_company_db?sslmode=require}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:neondb_owner}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:npg_drpuC7gIG0Nw}

###JPA Config
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.properties.hibernate.dialect=${SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT:org.hibernate.dialect.PostgreSQLDialect}
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL:true}
spring.jpa.properties.hibernate.format_sql=${SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL:true}
#
#logging.level.org.springframework.security=DEBUG
#
##jwt.secret-key= sddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddqwddscdc
#
#jwt.rsa-private-key=classpath:certs/PrivateKey.pem
#jwt.rsa-public-key =classpath:certs/PublicKey.pem
#
##server.port
#server.port=8080
#
##type of logger
#logging.framework=log4j
##logging.framework=slf4j
##logging.framework=custom

authentication.method=${AUTHENTICATION_METHOD:db}
otp.method=${OTP_METHOD:email}
main.service.url=${MAIN_SERVICE_URL:http://localhost:8081}
admin.secret.key=${ADMIN_SECRET_KEY:browns-Admin-Secret-2026}